name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: smarthelmetdb
          POSTGRES_USER: smartuser
          POSTGRES_PASSWORD: smartpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U smartuser -d smarthelmetdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -p 5432 -U smartuser; do
            sleep 2
          done

      - name: Set environment variables
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/smarthelmetdb" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=smartuser" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=smartpass" >> $GITHUB_ENV

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Run tests with Maven Wrapper
        run: ./mvnw test

      - name: Show test results (if failed)
        if: failure()
        run: |
          echo "=== Surefire Report ==="
          cat target/surefire-reports/*.txt || true
